### ISSUE TITLE
Useless bot.

### ISSUE THREAD

**Issue by franc-ist** [marcorennmaus/DiscordBot#1]
# Worst thing I have ever seen
- And made by a German, too!

**Comment by marcorennmaus** [comment]
lmao

**Comment by franc-ist** [comment]
# **You know it's true!**

**Comment by marcorennmaus** [comment]
You took your Bot's sourcecode from the Red Discordbot lmao

**Comment by franc-ist** [comment]
fight me

**Comment by marcorennmaus** [comment]
(ง❍v❍)ง

**Comment by GiovanniMCMXCIX** [comment]
shut up francis u fag
